name: Laporan Pusintras

on:
  schedule:
    # Menjalankan setiap hari pada pukul 17:00 UTC (00.00 WIB)
    - cron: '0 * * * *'

  push:
    branches:
      - main  # Jalankan ketika ada push ke branch main
permissions:
  contents: write
jobs:
  get_data_strategi:
    runs-on: ubuntu-22.04  # Menjalankan di mesin Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout kode dari repository

      - name: Set up Python 3.12.1
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.1'  # Menentukan versi Python yang digunakan

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies dari file requirements.txt (jika ada)

      - name: Run the Python script to get Data
        run: python main.py  # Jalankan file Python yang menghasilkan pickle

      - name: Create output folder and move pickle file
        run: |
          mkdir -p output  # Membuat folder output jika belum ada
          mv *.parquet output/

      - name: Commit and push pickle files to repository
        run: |
          git config --global user.name "izzuddinfa"
          git config --global user.email "izzuddinfathin@gmail.com"
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git add output/*.parquet  # Menambahkan semua file pickle di folder output
          git commit -m "add new data"  # Commit perubahan
          git push https://izzuddinfa:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
